services:

  postgres:
    image: postgres:18
    container_name: nexus-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nexus
    volumes:
      - nexus-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d nexus"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - nexus-db-network

  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: nexus-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__NexusDatabase: Host=postgres;Port=5432;Database=nexus;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5160:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nexus-app-network
      - nexus-db-network

  auth:
    build:
      context: ./src/Auth
      dockerfile: Dockerfile
    container_name: nexus-auth
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: nexus_auth
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nexus-app-network
      - nexus-db-network

networks:
  nexus-app-network:
    name: nexus-app-network
    driver: bridge

  nexus-db-network:
    name: nexus-db-network
    driver: bridge

volumes:
  nexus-postgres-data:
    external: true
